name: Check for Secrets

on:
  pull_request:
    branches:
      - dev  # Make sure this matches the branch you are merging into

jobs:
  secrets-scan:
    name: Scan for Secrets
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Install git-secrets
      run: |
        git clone https://github.com/msalemcode/git-secrets.git
        cd git-secrets && sudo make install

    - name: Set PATH for git-secrets
      run: |
        echo "/usr/local/bin" >> $GITHUB_PATH  # Assuming `make install` installs it to /usr/local/bin

    - name: Configure git-secrets
      run: |
        git secrets --install
        git secrets --register-aws
        git secrets --register-azure

    - name: Run git-secrets to scan for sensitive data
      run: git secrets --scan --recursive
